### ISSUE TITLE
Python3 install does not recognize ; as comments in config

### ISSUE THREAD

**Issue by cbc02009** [Klipper3d/klipper#4773]
Running Klipper v0.10.0-22-gcc63fd51 on Ubuntu 21.04. Manually installed.

updated the virtual environment to python 3 with the following process:

```
sudo systemctl stop klipper
rm -rf klippy-env
mkdir klippy-env
virtualenv klippy-env/
klippy-env/bin/pip install -r klipper/scripts/klippy-requirements.txt
sudo systemctl start klipper
```

No changes were made to the config, but now I'm getting the following error:
```
Config error
Traceback (most recent call last):
  File "/home/chris/klipper/klippy/configfile.py", line 35, in _get_wrapper
    v = parser(self.section, option)
  File "/usr/lib/python3.9/configparser.py", line 823, in getfloat
    return self._get_conv(section, option, float, raw=raw, vars=vars,
  File "/usr/lib/python3.9/configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.9/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: could not convert string to float: '10 ; MagProbe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/klipper/klippy/klippy.py", line 157, in _connect
    self._read_config()
  File "/home/chris/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/chris/klipper/klippy/klippy.py", line 130, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/chris/klipper/klippy/extras/quad_gantry_level.py", line 128, in load_config
    return QuadGantryLevel(config)
  File "/home/chris/klipper/klippy/extras/quad_gantry_level.py", line 31, in __init__
    self.horizontal_move_z = config.getfloat("horizontal_move_z", 5.0)
  File "/home/chris/klipper/klippy/configfile.py", line 65, in getfloat
    return self._get_wrapper(self.fileconfig.getfloat, option, default,
  File "/home/chris/klipper/klippy/configfile.py", line 39, in _get_wrapper
    raise error("Unable to parse option '%s' in section '%s'"
configparser.Error: Unable to parse option 'horizontal_move_z' in section 'quad_gantry_level'
```

Looks like it's not using the ; as a comment delimiter anymore?

I've attached the klippy.log file:
[klippy.log](https://github.com/Klipper3d/klipper/files/7296195/klippy.log)

**Comment by cbc02009** [comment]
Fixed in c7b65f50

**Comment by drveni** [comment]
my ender 3 v2 not longer work on klipper(cannot connect from fluidd to printer, say MCU error).... same/similar phyton errors.... i'm not sure maybe is locale problem.... still didn't fix... i gonna try again thx to  
cbc02009 (at first im think its mainboard error .. but octoprint and jyers works)
